version: '3'

services:
  nginx:
    image: nginx:1.14
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  differ-redis:
    image: redis:alpine
    ports:
        - 6379:6379
    volumes:
        - differ-db-vol:/data

volumes:
  differ-db-vol:
