version: "3.7"
services:
  # API server that the jiranator-app will use for async requests to jira
  differ-api:
    image: bubthegreat/differ-api
    hostname: differ-api
    build:
      context: api-differ/
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.frontend.rule=Host:api.differ.localhost"
    networks:
      - differ-backend
    ports:
      - 8000:8000

  # Application service for the frontend that users will interact with
  differ-app:
    image: bubthegreat/differ-app
    hostname: differ-app
    build:
      context: app-differ/
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.frontend.rule=Host:app.differ.localhost"
    ports:
      - 80:4200
    networks:
      - differ-backend
    depends_on:
      - differ-api
      - differ-redis

  # Database for the application and backend to save to.
  differ-redis:
      hostname: differ-redis
      image: redis:alpine
      deploy:
          replicas: 1
          restart_policy:
              condition: on-failure
      ports:
          - 6379:6379
      volumes:
          - differ-db-vol:/data
      networks:
        - differ-backend

networks:
  differ-backend:
    driver: overlay

volumes:
  differ-db-vol: