- op: replace
  path: /spec/rules/0/host
  value: skillmatrix.bubtaylor.com
- op: add
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: letsencrypt-prod
- op: add
  path: /spec/tls
  value:
    - hosts:
      - skillmatrix.bubtaylor.com
      secretName: differ-prod-tls
