apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: differ-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: differ
  source:
    repoURL: git@gitlab.com:bubthegreat/differ.git
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
