
apiVersion: v1
kind: Service
metadata:
  name: differ-app
  namespace: differ
spec:
  selector:
    app: differ-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
