- op: replace
  path: /spec/rules/0/host
  value: qa-skillmatrix.bubtaylor.com
- op: add
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: letsencrypt-prod
- op: add
  path: /spec/tls
  value:
    - hosts:
      - qa-skillmatrix.bubtaylor.com
      secretName: differ-qa-tls
