apiVersion: v1
kind: ConfigMap
metadata:
  name: differ-api-config
data:
  CORS_ORIGINS: "https://staging-skillmatrix.bubtaylor.com"
  JWT_SECRET_KEY: "staging_secret_key_change_me"
  BYPASS_AUTH: "false"
